services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: menstrual_tracker_app
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=menstrual_tracker
      - DB_USERNAME=user
      - DB_PASSWORD=secret
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: menstrual_tracker_db
    environment:
      MYSQL_DATABASE: menstrual_tracker
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootsecret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: menstrual_tracker_nginx
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge